export interface Product {
  id: string
  name: string
  description: string
  category: string
  image: string
}

export const categories = [
  { id: "all", name: "All Products" },
  { id: "hospital", name: "Hospital Equipment" },
   {id: "bed-strecher", name: "Bed & Stretchers"},
    {id: "ot-light", name: "O.T Lights"},
  { id: "surgical", name: "Surgical Instruments" },
  { id: "disposable", name: "Disposable Medical Supplies" },
  { id: "diagnostic", name: "Diagnostic Equipment" },
  { id: "patient-care", name: "Patient Care Products" },

]

export const products: Product[] = [
  // Surgical Instruments
  {
    id: "1",
    name: "scalpel set",
    description: "Precision stainless steel scalpel set with interchangeable blades for surgical procedures.",
    category: "surgical",
    image: "/images/products/scalpel.jpg",
  },

  {
    id: "2",
    name: "Surgical Forceps",
    description: "High-quality surgical forceps for tissue handling during operations.",
    category: "surgical",
    image: "/images/products/forceps.jpg",
  },
  {
    id: "3",
    name: "Needle Holders",
    description: "Ergonomic needle holders for secure suturing in surgical procedures.",
    category: "surgical",
    image: "/images/products/needle-holders.jpg",
  },
  {
    id: "4",
    name: "Surgical Scissors",
    description: "Sharp, durable surgical scissors for cutting tissue and sutures.",
    category: "surgical",
    image: "/images/products/scissors.jpg",
  },
  // Hospital Equipment
  {
    id: "5",
    name: "Bed Headed Panels",
    description: "",
    category: "hospital",
    image: "/images/products/bedheaded_panel-bhs-11090.png",
  },
  // {
  //   id: "6",
  //   name: "IV Stand - Adjustable",
  //   description: "Height-adjustable IV stand with multiple hooks for fluid administration.",
  //   category: "hospital",
  //   image: "/images/products/iv-stand.jpg",
  // },
  // {
  //   id: "7",
  //   name: "Medical Trolley",
  //   description: "Multi-tier medical trolley for organizing equipment and supplies.",
  //   category: "hospital",
  //   image: "/images/products/trolley.jpg",
  // },
  // {
  //   id: "8",
  //   name: "Examination Table",
  //   description: "Padded examination table with adjustable height and paper roll holder.",
  //   category: "hospital",
  //   image: "/images/products/exam-table.jpg",
  // },
   {
    id: "6",
    name: "O.T Pendant",
    description: "",
    category: "hospital",
    image: "/images/products/ot-pendant.png",
  },
     {
    id: "7",
    name: "I.C.U & Wards Curtaining",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-7.png",
  },
  {
    id: "8",
    name: "E.N.T & Neuro Microscopes",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-8.png",
  },
  {
    id: "9",
    name: "Otho & Neuro Attachments",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-9.png",
  },

   {
    id: "10",
    name: "Physiotherapy goods",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-10.png",
  },
  {
    id: "11",
    name: "General Surgical Goods",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-11.png",
  },
  {
    id: "12",
    name: "Mannequins & All Dummies",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-12.png",
  },

{
    id: "13",
    name: "LED Photo Therapy Machine Single Surface/ Double Surface",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-13.png",
  },

  {
    id: "14",
    name: "Baby Incubator ",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-14.png",
  },

{
    id: "15",
    name: "Horizontal & Vertical Autoclave ",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-15.png",
  },
  {
    id: "16",
    name: "E.T.O Sterilizer",
    description: "",
    category: "hospital",
    image: "/images/products/16.png",
  },
  {
    id: "17",
    name: "Suction Machine",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-17.png",
  },
  {
    id: "18",
    name: "Anesthesia Workstation & Trolleys",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-18.png",
  },
  {
    id: "19",
    name: "Ventilator Machine ",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-19.png",
  },
  {
    id: "20",
    name: "Automatic External Defibrillator",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-20.png",
  },
  {
    id: "21",
    name: "BS Standard(Model: Amber) Front Loaded With Probe",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-21.png",
  },
  {
    id: "22",
    name: "PB Standard(Model: Sapphire) Front Loaded With Probe",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-22.png",
  },
  {
    id: "23",
    name: "Parkodex With Probe (Hook Loose Type)7",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-23.png",
  },
  {
    id: "24",
    name: "DIN Standard (Model: Jasper) with Probe",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-24.png",
  },
  {
    id: "25",
    name: "BPC Flow Meter",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-25.png",
  },
  {
    id: "26",
    name: "Theater Suction Trolley",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-26.png",
  },
  {
    id: "27",
    name: "Vacuum Regulator",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-27.png",
  },
  {
    id: "28",
    name: "Vacuum Jar",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-28.png",
  },
  {
    id: "29",
    name: "Avsu Zonal Valve Box",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-29.png",
  },
  {
    id: "30",
    name: "Dental Chair ",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-30.png",
  },
  {
    id: "31",
    name: "Microscopes, Centrifuge, Incubator, Hot Air Oven & All Scientific Goods",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-31.png",
  },
  {
    id: "32",
    name: "Hematology Analyzer",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-32.png",
  },
  {
    id: "33",
    name: "Electrolyte Analyzer",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-33.png",
  },
  {
    id: "34",
    name: "Arterial Blood Gas Machine",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-34.png",
  },
  {
    id: "35",
    name: "Biochemistry Analyzer",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-35.png",
  },
  {
    id: "36",
    name: "Elisa Reader & Washer",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-36.png",
  },
  {
    id: "37",
    name: "Baby Radiant Warmer",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-37.png",
  },
  {
    id: "38",
    name: "LED Photo Therapy Machine Single Surface/ Double Surface",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-38.png",
  },
  {
    id: "39",
    name: "New & Pre-Owned C.R System",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-39.png",
  },
  {
    id: "40",
    name: "New 7 Pre-Owned C.Arm Machines",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-40.png",
  },
  {
    id: "41",
    name: "New & Pre-Owned Diagnostic Ultrasound Scanners",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-41.png",
  },
   {
    id: "42",
    name: "New & Pre-Owned Gastroscopy",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-42.png",
  },
   {
    id: "43",
    name: "New & Pre-Owned Bubble C-Pap",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-43.png",
  },
   {
    id: "44",
    name: "Syringe Pump",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-44.png",
  },
   {
    id: "45",
    name: "Oxygen Concentrators",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-45.png",
  },
   {
    id: "46",
    name: "New & Pre-Owned C.T Scan Machines",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-46.png",
  },
   {
    id: "47",
    name: "New & Pre-Owned M.R.I Scan Machines",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-47.png",
  },
   {
    id: "48",
    name: "New & Pre-Owned X.Ray Scan Machines",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-48.png",
  },
   {
    id: "49",
    name: "Spine Board",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-49.png",
  },
   {
    id: "50",
    name: "Four Fold Stretcher",
    description: "",
    category: "bed-strecher",
    image: "/images/products/hospital-50.png",
  },
   {
    id: "51",
    name: "Two Fold Stretcher ",
    description: "",
    category: "bed-strecher",
    image: "/images/products/hospital-51.png",
  },
   {
    id: "52",
    name: "Four Fold Stretcher",
    description: "",
    category: "bed-strecher",
    image: "/images/products/hospital-52.png",
  },
   {
    id: "53",
    name: "Fogger Machine",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-53.png",
  },
   {
    id: "54",
    name: "Five Para Monitor",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-54.png",
  },
   {
    id: "55",
    name: "Three Para Monitor",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-55.png",
  },
   {
    id: "56",
    name: "E.C.G Machine",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-56.png",
  },
   {
    id: "57",
    name: "New & Pre-Owned Defibrillator",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-57.png",
  },
   {
    id: "58",
    name: "Instrument Trolley All S.S",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-58.png",
  },
   {
    id: "59",
    name: "Instrument Trolley Box Type",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-59.png",
  },
   {
    id: "60",
    name: "Instrument Trolley Box Type",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-60.png",
  },
   {
    id: "61",
    name: "Instrument Trolley Three Shelf",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-61.png",
  },
   {
    id: "62",
    name: "Dressing Trolley All S.S",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-62.png",
  },
   {
    id: "63",
    name: "E.C.G Trolly ",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-63.png",
  },
   {
    id: "64",
    name: "Line Trolley ",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-64.png",
  },
   {
    id: "65",
    name: "Laparoscopy Trolley ",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-65.png",
  },
   {
    id: "66",
    name: "Food Table",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-66.png",
  },
   {
    id: "67",
    name: "Boi-Waste Trolley",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-67.png",
  },
   {
    id: "68",
    name: "Mayo's Trolley",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-68.png",
  },
   {
    id: "69",
    name: "Instrument Cabinet",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-69.png",
  },
   {
    id: "70",
    name: "Three Seater Chrome ",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-70.png",
  },
   {
    id: "71",
    name: "Three Seater",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-71.png",
  },
   {
    id: "72",
    name: "Examination Couch Deluxe",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-72.png",
  },
   {
    id: "73",
    name: "Cylinder Trolley",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-73.png",
  },
   {
    id: "74",
    name: "Revolving Stool Super Deluxe",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-74.png",
  },
   {
    id: "75",
    name: "Revolving Stool Deluxe",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-75.png",
  },
   {
    id: "76",
    name: "Bed Side Locker S.S",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-76.png",
  },
   {
    id: "77",
    name: "Bed Side Locker Semi Deluxe",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-77.png",
  },
   {
    id: "78",
    name: "Bed Side Locker Deluxe ",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-78.png",
  },
  
{
    id: "79",
    name: "Bed Side Locker ABS Type",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-79.png",
  },
  {
    id: "80",
    name: "Wheel Chair ",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-80.png",
  },
  {
    id: "81",
    name: "Stretcher Trolley ",
    description: "",
    category: "bed-strecher",
    image: "/images/products/hospital-81.png",
  },
  {
    id: "82",
    name: "Stretcher Trolley Deluxe",
    description: "",
    category: "bed-strecher",
    image: "/images/products/hospital-82.png",
  },
  {
    id: "83",
    name: "Stretcher  Cum Chair",
    description: "",
    category: "bed-strecher",
    image: "/images/products/hospital-83.png",
  },
  {
    id: "84",
    name: "Emergency Patient Trolley ",
    description: "",
    category: "bed-strecher",
    image: "/images/products/hospital-84.png",
  },
  {
    id: "85",
    name: "Ambulance Stretcher",
    description: "",
    category: "bed-strecher",
    image: "/images/products/hospital-85.png",
  },
  {
    id: "86",
    name: "Scrub Station with Sensor& with our sensor",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-86.png",
  },
  {
    id: "87",
    name: "Attendant Bed Cum Chair",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-87.png",
  },
  {
    id: "88",
    name: "Blood Donating Chair ",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-88.png",
  },
  {
    id: "89",
    name: "Crash Cart with ABS Drawers",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-89.png",
  },
  {
    id: "90",
    name: "Hospital Three Fold Screen",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-90.png",
  },
  {
    id: "91",
    name: "Crash Cart with S.S Drawers",
    description: "",
    category: "hospital",
    image: "/images/products/hospital-91.png",
  },
  
//Bed and Stretchers

  {
    id: "93",
    name: "I.C.U Bed Five Functional Electric",
    description: "",
    category: "bed-strecher",
    image: "/images/products/bed-93.jpg",
  },

   {
    id: "94",
    name: "I.C.U Bed Five Functional Electric (Eco Model)",
    description: "",
    category: "bed-strecher",
    image: "/images/products/bed-94.png",
  },
   {
    id: "95",
    name: "I.C.U Bed Five Functional Manual",
    description: "",
    category: "bed-strecher",
    image: "/images/products/bed-95.png",
  },
   {
    id: "96",
    name: "I.C.U Bed Five Functional Electric",
    description: "",
    category: "bed-strecher",
    image: "/images/products/bed-96.png",
  },
   {
    id: "97",
    name: "I.C.U Bed Five Functional Super Deluxe",
    description: "",
    category: "bed-strecher",
    image: "/images/products/bed-97.png",
  },
   {
    id: "98",
    name: "I.C.U Bed Five Bed Deluxe A",
    description: "",
    category: "bed-strecher",
    image: "/images/products/bed-98.png",
  },
   {
    id: "99",
    name: "I.C.U Bed Fowler Bed Deluxe",
    description: "",
    category: "bed-strecher",
    image: "/images/products/bed-99.png",
  },
   {
    id: "100",
    name: "I.C.U Bed Fowler Bed Eco",
    description: "",
    category: "bed-strecher",
    image: "/images/products/bed-100.png",
  },
   {
    id: "101",
    name: "I.C.U Bed Semi Fowler Bed Electric ",
    description: "",
    category: "bed-strecher",
    image: "/images/products/bed-101.png",
  },
   {
    id: "102",
    name: "I.C.U Bed Semi Fowler Bed Super Dulex",
    description: "",
    category: "bed-strecher",
    image: "/images/products/bed-102.png",
  },
   {
    id: "103",
    name: "I.C.U Bed Semi Fowler Bed Dulex",
    description: "",
    category: "bed-strecher",
    image: "/images/products/bed-103.png",
  },
   {
    id: "104",
    name: "I.C.U Bed Semi Fowler Bed Eco Model",
    description: "",
    category: "bed-strecher",
    image: "/images/products/bed-104.png",
  },
   {
    id: "105",
    name: "I.C.U Bed Plain Super Delux",
    description: "",
    category: "bed-strecher",
    image: "/images/products/bed-105.png",
  },
   {
    id: "106",
    name: "I.C.U Bed Plain Delux",
    description: "",
    category: "bed-strecher",
    image: "/images/products/bed-106.png",
  },
   {
    id: "107",
    name: "I.C.U Bed Plain (Eco Model)",
    description: "",
    category: "bed-strecher",
    image: "/images/products/bed-107.png",
  },
  {
    id: "108",
    name: "Pediatric Bed",
    description: "",
    category: "bed-strecher",
    image: "/images/products/bed-108.png",
  },
  {
    id: "109",
    name: "Baby Bassinet",
    description: "",
    category: "bed-strecher",
    image: "/images/products/bed-109.png",
  },
  
  {
    id: "110",
    name: "OT Electric + Manual",
    description: "",
    category: "bed-strecher",
    image: "/images/products/bed-110.png",
  },
  {
    id: "111",
    name: "OT Table Hydraulic",
    description: "",
    category: "bed-strecher",
    image: "/images/products/bed-111.png",
  },
  {
    id: "112",
    name: "OT Table C-Arm Electric & Manual",
    description: "",
    category: "bed-strecher",
    image: "/images/products/bed-112.png",
  },
  {
    id: "113",
    name: "OT Table C-Arm Hydraulic",
    description: "",
    category: "bed-strecher",
    image: "/images/products/bed-113.png",
  },
  {
    id: "114",
    name: "Delivery Table",
    description: "",
    category: "bed-strecher",
    image: "/images/products/bed-114.png",
  },
  {
    id: "115",
    name: "Delivery Table Three Fold",
    description: "",
    category: "bed-strecher",
    image: "/images/products/bed-115.png",
  },
  {
    id: "116",
    name: "Delivery Bed",
    description: "",
    category: "bed-strecher",
    image: "/images/products/bed-116.png",
  },
   {
    id: "117",
    name: "Delivery Table Hydraulic Deluxe ",
    description: "",
    category: "bed-strecher",
    image: "/images/products/bed-117.png",
  },
   {
    id: "118",
    name: "Delivery Table Electric + Manual",
    description: "",
    category: "bed-strecher",
    image: "/images/products/bed-118.png",
  },
  
   //ot lights
   {
    id: "119",
    name: "Mobile O.T Light",
    description: "",
    category: "ot-light",
    image: "/images/products/ot-119.png",
  },
  
     {
    id: "120",
    name: "O.T Light Single Dome Halogen",
    description: "",
    category: "ot-light",
    image: "/images/products/ot-120.png",
  },
   {
    id: "121",
    name: "O.T Light Twin Halogen ",
    description: "",
    category: "ot-light",
    image: "/images/products/ot-121.png",
  },
   {
    id: "122",
    name: "O.T Light Single/ Double Dome",
    description: "",
    category: "ot-light",
    image: "/images/products/ot-122.png",
  },
   {
    id: "123",
    name: "O.T Light Single/ Double Dome",
    description: "",
    category: "ot-light",
    image: "/images/products/ot-123.png",
  },
   {
    id: "124",
    name: "LED O.T Light Twin ",
    description: "",
    category: "ot-light",
    image: "/images/products/ot-124.png",
  },
  
  //Disposable Medical Supplies
  {
    id: "125",
    name: "Surgical Gloves - Box of 100",
    description: "Powder-free latex surgical gloves, sterile and individually wrapped.",
    category: "disposable",
    image: "/images/products/gloves.jpg",
  },
  {
    id: "126",
    name: "Surgical Masks - Pack of 50",
    description: "3-ply disposable surgical masks with ear loops.",
    category: "disposable",
    image: "/images/products/masks.jpg",
  },
  {
    id: "127",
    name: "Syringes - Pack of 100",
    description: "Sterile disposable syringes in various sizes (1ml, 3ml, 5ml, 10ml).",
    category: "disposable",
    image: "/images/products/syringes.jpg",
  },
  {
    id: "128",
    name: "Surgical Drapes",
    description: "Sterile disposable surgical drapes for maintaining sterile field.",
    category: "disposable",
    image: "/images/products/drapes.jpg",
  },
  // Diagnostic Equipment
  {
    id: "129",
    name: "Digital Blood Pressure Monitor",
    description: "Automatic digital BP monitor with memory function and large display.",
    category: "diagnostic",
    image: "/images/products/bp-monitor.jpg",
  },
  {
    id: "130",
    name: "Pulse Oximeter",
    description: "Fingertip pulse oximeter for measuring blood oxygen levels.",
    category: "diagnostic",
    image: "/images/products/oximeter.jpg",
  },
  {
    id: "131",
    name: "Digital Thermometer",
    description: "Fast-reading digital thermometer with fever alert.",
    category: "diagnostic",
    image: "/images/products/thermometer.jpg",
  },
  {
    id: "132",
    name: "Stethoscope - Professional",
    description: "High-quality acoustic stethoscope for accurate auscultation.",
    category: "diagnostic",
    image: "/images/products/stethoscope.jpg",
  },
  // Patient Care Products
  {
    id: "133",
    name: "Wheelchair - Foldable",
    description: "Lightweight foldable wheelchair with comfortable cushioning.",
    category: "patient-care",
    image: "/images/products/wheelchair.jpg",
  },
  {
    id: "134",
    name: "Walking Aid - Crutches",
    description: "Adjustable aluminum crutches with comfortable arm pads.",
    category: "patient-care",
    image: "/images/products/crutches.jpg",
  },
  {
    id: "135",
    name: "Nebulizer Machine",
    description: "Portable nebulizer for respiratory medication delivery.",
    category: "patient-care",
    image: "/images/products/nebulizer.jpg",
  },
  {
    id: "136",
    name: "Bed Pan - Stainless Steel",
    description: "Durable stainless steel bed pan for patient care.",
    category: "patient-care",
    image: "/images/products/bedpan.jpg",
  },
]
